# Generated by Django 5.0.6 on 2024-06-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('CNPJ_CPF', models.IntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Celular', models.CharField(max_length=100)),
            ],
        ),
    ]
