# Generated by Django 5.0.3 on 2024-07-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientes_cnpj_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
