# Generated by Django 5.0.3 on 2024-07-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='CNPJ_CPF',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
